# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'arm-template-connection'
    subscriptionId: '140c982b-31da-401b-9652-d724a803076a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm-templates'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/thewahome/arm-templates/main/advanced/arm-deploy.json'
    overrideParameters: '-storagePrefix arm'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
